name = "fdtotg"
main = "index.js"
compatibility_date = "2026-08-23"
workers_dev = true

# Указываем, что твои HTML файлы лежат в папке public_html
[assets]
directory = "./public_html"

[vars]
ENVIRONMENT = "production"
