name = "fdtotg"
main = "index.js"
compatibility_date = "2026-08-23"
workers_dev = true

# Указываем правильное название папки со статикой
[assets]
directory = "./public"

[vars]
ENVIRONMENT = "production"
